# Generated by Django 5.1.3 on 2024-11-19 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Укажите наименование курса",
                        max_length=100,
                        null=True,
                        verbose_name="Наименование курса",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью",
                        null=True,
                        upload_to="ims/preview",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Укажите описание курса",
                        null=True,
                        verbose_name="Описание курса",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Курс",),
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_lesson",
                    models.CharField(
                        help_text="Укажите наименование урока",
                        max_length=100,
                        verbose_name="Наименование урока",
                    ),
                ),
                (
                    "preview_lesson",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью урока",
                        null=True,
                        upload_to="ims/preview",
                        verbose_name="Превью урока",
                    ),
                ),
                (
                    "description_lesson",
                    models.TextField(
                        blank=True,
                        help_text="Укажите описание урока",
                        null=True,
                        verbose_name="Описание урока",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Укажите ссылку на видео",
                        null=True,
                        verbose_name="Ссылка на видео",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите наименование курса",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ims.course",
                        verbose_name="Наименование курса",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Урок",),
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
