# Generated by Django 5.1.3 on 2024-12-04 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0002_course_owner_lesson_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_subscription",
                    models.CharField(
                        blank=True,
                        help_text="Укажите наименование подписки",
                        max_length=50,
                        null=True,
                        verbose_name="Наименование подписки",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Выберите наименование курса",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="ims.course",
                        verbose_name="Наименование курса",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите владельца подписки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец подписки",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Подписка",),
                "verbose_name_plural": "Подписки",
                "unique_together": {("user", "course")},
            },
        ),
    ]
