# Generated by Django 5.1.3 on 2024-12-10 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0003_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="update_course",
            field=models.ManyToManyField(
                blank=True,
                help_text="Укажите обновление курса",
                null=True,
                related_name="course_update",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обновление курса",
            ),
        ),
    ]
