# Generated by Django 5.1.3 on 2024-11-27 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0002_course_owner_lesson_owner"),
        ("users", "0003_remove_payment_course_remove_payment_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите оплаченный курс",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ims.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите оплаченный урок",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ims.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
